# Generated by Django 4.1.5 on 2023-02-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_end_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_category_name', models.CharField(max_length=120)),
                ('show_end_menu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='add_mid_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_category_name', models.CharField(max_length=120)),
                ('show_mid_menu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='add_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_top_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_category_name', models.CharField(max_length=120)),
                ('show_top_menu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('current_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('featured_photo', models.ImageField(upload_to='Media/Product_Images/Featured_image')),
                ('photo_1', models.ImageField(upload_to='Media/Product_Images/Other_Images')),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('featured_desc', models.TextField()),
                ('condition_desc', models.TextField()),
                ('return_policy_desc', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('select_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.add_color')),
                ('select_end_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.add_end_category')),
                ('select_mid_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.add_mid_category')),
                ('select_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.add_size')),
                ('select_top_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.add_top_category')),
            ],
        ),
        migrations.AddField(
            model_name='add_mid_category',
            name='select_top_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.add_top_category'),
        ),
        migrations.AddField(
            model_name='add_end_category',
            name='select_mid_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.add_mid_category'),
        ),
    ]
