# Generated by Django 4.1.5 on 2023-02-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_color',
            options={'verbose_name_plural': '5 - Add Color'},
        ),
        migrations.AlterModelOptions(
            name='add_country',
            options={'verbose_name_plural': '6 - Add Country'},
        ),
        migrations.AlterModelOptions(
            name='add_end_category',
            options={'verbose_name_plural': '3 - Add End Category'},
        ),
        migrations.AlterModelOptions(
            name='add_mid_category',
            options={'verbose_name_plural': '2 - Add Mid Category'},
        ),
        migrations.AlterModelOptions(
            name='add_product',
            options={'verbose_name_plural': '7 - Add Product'},
        ),
        migrations.AlterModelOptions(
            name='add_size',
            options={'verbose_name_plural': '4 - Add Size'},
        ),
        migrations.AlterModelOptions(
            name='add_top_category',
            options={'verbose_name_plural': '1 - Add Top Category'},
        ),
        migrations.AddField(
            model_name='add_product',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Product_Images/Other_Images'),
        ),
        migrations.AddField(
            model_name='add_product',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Product_Images/Other_Images'),
        ),
        migrations.AddField(
            model_name='add_product',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Product_Images/Other_Images'),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Product_Images/Other_Images'),
        ),
    ]
