# Generated by Django 4.1.5 on 2023-02-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_alter_add_product_select_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_social_media_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=10000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=10000, null=True)),
                ('youtube', models.CharField(blank=True, max_length=10000, null=True)),
                ('watsapp', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
