# Generated by Django 4.1.5 on 2023-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0006_add_social_media_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_favicon', models.ImageField(upload_to='Media/website_images/')),
            ],
        ),
        migrations.CreateModel(
            name='add_footer_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_copyright', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
                ('map_iframe', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='add_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_logo', models.ImageField(upload_to='Media/website_images/')),
            ],
        ),
    ]
