# Generated by Django 4.1.5 on 2023-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_add_favicon_add_footer_contact_add_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_footer_contact',
            name='contact_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
