# Generated by Django 4.1.7 on 2023-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0008_alter_add_footer_contact_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
