# Generated by Django 4.1.7 on 2023-02-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0009_add_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/website_images/slider')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
