# Generated by Django 4.1.7 on 2023-02-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0010_add_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_slider',
            name='button_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='add_slider',
            name='content',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='add_slider',
            name='heading',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
