# Generated by Django 4.1.7 on 2023-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0011_add_slider_button_text_add_slider_button_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
