# Generated by Django 4.1.5 on 2023-02-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_cnic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='cnic',
        ),
    ]
