# Generated by Django 4.1.5 on 2023-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_myuser_is_active_myuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
