# Generated by Django 4.1.5 on 2023-02-10 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_alter_add_color_options_alter_add_country_options_and_more'),
        ('account', '0005_myuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.add_product')),
            ],
        ),
    ]
