# Generated by Django 4.1.5 on 2023-02-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_productsave_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsave',
            name='color',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productsave',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsave',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
