# Generated by Django 4.1.5 on 2023-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_productsave_color_productsave_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsave',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
