# Generated by Django 4.1.5 on 2023-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_productsave_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsave',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
