# Generated by Django 4.1.5 on 2023-02-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='products',
            field=models.ManyToManyField(related_name='transactions', to='account.productsave'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=36),
        ),
    ]
