# Generated by Django 4.1.5 on 2023-02-13 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_transaction_date_alter_transaction_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
