# Generated by Django 4.1.7 on 2023-02-16 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_myuser_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')]),
        ),
    ]
