# Generated by Django 4.1.7 on 2023-02-17 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0008_alter_add_footer_contact_contact_no'),
        ('account', '0016_alter_myuser_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Not Available', 'Not Available')], max_length=50, null=True)),
                ('get_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customadmin.add_product')),
            ],
        ),
    ]
