# Generated by Django 4.1.7 on 2023-02-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsave',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
