# Generated by Django 4.1.7 on 2023-02-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
