# Generated by Django 4.1.7 on 2023-02-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_orderproduct_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='shipping',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
