# Generated by Django 4.1.7 on 2023-02-19 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_orderproduct_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsave',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
