# Generated by Django 4.1.7 on 2023-02-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_productsave_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsave',
            unique_together=set(),
        ),
    ]
