# Generated by Django 4.1.7 on 2023-02-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_productsave_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsave',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
